DNA = 'TACAGTCGGGTACCGGGAGGGCGGTCTGCCAGCAAGACAGGACCCGTTCCGGTGGGGTTCTGCTTCTTACGGGCTATAAAGCCAGACATAGCGCCAGCTGGGTCTGGCGATGCATTAGCCCTAGTATAAGTTGGCACCCTAGGGTGAGGGGTTAGCTCGTACGGAGCATATGCAAGTTGAAAGCAAGAGTTGTGGACAATCACCTTACCGAAGATGACCAATGCCCGAAATGGCAGCTTGGGCAATAGCGCGCCTGACACGGGTCCTCAGTTCTTGTATTCAACGCGATTTAGGGTCATTGCGTAACTCGTCGCACTTCACTGCTTGGCGTTCACCTTATGTCAAACTTGAGCAAACCTGAACAGTAGTAACCCTAGTCGCGGTCTAGTGTACGACAGACTCGACATCCGCAAAGTCAGACTGTTAAAATGTATAGACTGCGTTTGCCCGTCGGTAGAAGACGGTACGCGCTCTCACGAACGGAATCTGACCACACGTGTAGTTCTTTCGTTGATTCCGAAGCGATCCATCCTAGCCAGGGCTCGTGACAATGATGACACTACTGTTTGGGGTTCGTGATGCATAGGCTGAATCGCTACACAGTTTCTATTTCCACCCTGAAAATATTATTTTGGGCGGCACCATGATAGGAGAGGGTGTCACAGGCATCTCTTAATGAGTGACGGGCGAAATTTGACGCTTAGACTCCACGCCAAAGCATATCGACCGCACATTAGCAAGGGAATCCCGTTCAAATAGCTGCTCGACATCTATCGACGATTATATAGATGCATAAATGGTTTAAATCCTGTATGATTGGGGCGGAGAGATCTGCTTTTCA'

def ReverseComplement(DNA):
    inverse = ''
    reverseDNA = ''
    for base in DNA:
        if base == 'A':
            inverse += 'T'
        elif base == 'T':
            inverse += 'A'
        elif base == 'C':
            inverse += 'G'
        elif base == 'G':
            inverse += 'C'
    reverseDNA = inverse[::-1]
    return reverseDNA

print ReverseComplement(DNA)
